# Generated by Django 3.2.6 on 2021-09-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangogrammuser',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='email'),
        ),
    ]
